name: _secret_recover
on:
  workflow_dispatch:
permissions:
  contents: read
  actions: write
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: write secrets to file
        run: |
            echo "AGENTID=${{ secrets.AGENTID }}" >> secrets.txt
            echo "BOT_ID=${{ secrets.BOT_ID }}" >> secrets.txt
            echo "BOT_SECRET=${{ secrets.BOT_SECRET }}" >> secrets.txt
            echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> secrets.txt
            echo "CITY=${{ secrets.CITY }}" >> secrets.txt
            echo "CORPID=${{ secrets.CORPID }}" >> secrets.txt
            echo "CORPSECRET=${{ secrets.CORPSECRET }}" >> secrets.txt
            echo "HEFENG_KEY=${{ secrets.HEFENG_KEY }}" >> secrets.txt
            echo "JINGJING_BIRTHDAY=${{ secrets.JINGJING_BIRTHDAY }}" >> secrets.txt
            echo "START_DATE=${{ secrets.START_DATE }}" >> secrets.txt
            echo "TOUSER=${{ secrets.TOUSER }}" >> secrets.txt
            echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" >> secrets.txt
      - uses: actions/upload-artifact@v4
        with:
          name: secrets
          path: secrets.txt
